terra-money/fcd

- .github/workflows/default.yml
> Add package audit in CI

- .github/workflows/default.yml
> Publish master on docker hub

- Dockerfile
related to https://github.com/terra-project/ops/issues/57
> Add swagger and apidoc built assets to docker image

- src/e2etest/tx.spec.ts
- src/scripts/getSwaps.ts
- src/service/transaction/getTxList.ts
- src/service/transaction/helper.ts
- src/service/transaction/index.ts
- src/service/transaction/parseMsg.ts
- src/service/transaction/parseTx.ts
- src/types/tx.d.ts
By Terra data structure, we should handle tax per msg, not per transaction.
> Handle tax by each message instead of by transaction

- Dockerfile
- README.md
- package.json
- src/collector/gov/collectProposal.ts
- src/collector/gov/removeProposal.ts
- src/collector/gov/saveProposal.ts
- src/controller/DashboardController.ts
- src/controller/GovernanceController.ts
- src/controller/MarketController.ts
- src/controller/StakingController.ts
- src/controller/TransactionController.ts
- src/controller/TreasuryController.ts
- src/e2etest/tx.spec.ts
- src/scripts/getSwaps.ts
- src/scripts/mergeSwaggerFile.ts
- src/service/transaction/getTxList.ts
- src/service/transaction/helper.ts
- src/service/transaction/index.ts
- src/service/transaction/parseMsg.ts
- src/service/transaction/parseTx.ts
- src/types/tx.d.ts
- yarn.lock
1. Add tax info to `/msg` tx list
2. Add swagger merger for lcd and fcd
3. Update Dockerfile to generate apidoc and swagger
> Updating master

- package.json
- sql/customIndex.sql
- src/collector/staking/validatorDetails.ts
- src/controller/TransactionController.ts
- src/createApp.ts
- src/orm/ValidatorInfoEntity.ts
- src/scripts/mergeSwaggerFile.ts
- src/scripts/testUrls.ts
- src/server.ts
- yarn.lock
1. Fix unique constraint issue in validator cache
2. Add `/health` for websocket only options
3. Add url checker which call every GET url from swagger to check if its live or not
4. Sql for custom db index
> BugFix and Improvement (issues 47-49)

- README.md
- package.json
- sql/customIndex.sql
- src/collector/staking/validatorDetails.ts
- src/config.ts
- src/controller/TransactionController.ts
- src/createApp.ts
- src/orm/ValidatorInfoEntity.ts
- src/scripts/mergeSwaggerFile.ts
- src/scripts/testUrls.ts
- src/server.ts
- yarn.lock
1. Fix unique constraint issue in validator cache
2. Add `/health` for websocket only options
3. Add url checker which call every GET url from swagger to check if its live or not
4. Sql for custom db index
> Updating master 

- Dockerfile
> Use npm instead of yarn as entrypoint

- package.json
- src/collector/block/block.ts
- src/collector/collector.ts
- src/controller/TransactionController.ts
- src/e2etest/tx.spec.ts
- src/scripts/generateApidoc.ts
- src/service/transaction/getTxList.ts
SQL Injection vulnerability was also reported by SCVSoft (https://scvsoft.net/)
> Updating master (includes SQL Injection vulnerability fix)

- package-lock.json
- package.json
- src/collector/getAddressFromMsg.ts
Index transaction by feeder address for oracle/MsgAggregateExchangeRateVote and oracle/MsgAggregateExchangeRatePrevote messages.
> Index oracle aggregate vote msgs by account

- src/collector/getAddressFromMsg.ts
> fix(collector): validator_address should be extracted for MsgWithdrawValidatorCommission

- package-lock.json
- package.json
- src/collector/block/accountTx.ts
- src/collector/getAddressFromMsg.ts
- src/collector/gov/saveProposal.ts
- src/e2etest/lcd.spec.ts
- src/lib/lcd.ts
- src/orm/DashboardEntity.ts
- src/orm/ProposalEntity.ts
- src/service/governance/getDeposits.ts
- src/service/governance/getVotes.ts
- src/service/governance/helper/voteSummary.ts
- src/service/transaction/parseMsg.ts
- src/types/governance.d.ts
Collector: Index AccountTx by contract address
ProposalEntity: voteTxs depositTxs has been replaced to votes and deposits
API: /v1/msgs will parse and return detail for contract messages
> AccountTx index by contract address and more

- src/service/dashboard/getStakingReturn.ts
Not affected in columbus-4 but columbus-3
> fix(dashboard): possible divide by zero

- package-lock.json
- package.json
- src/collector/block/tx.ts
- src/collector/collector.ts
- src/collector/staking/collectValidatorReturn.ts
- src/collector/staking/validatorDetails.ts
- src/config.ts
- src/controller/WasmController.ts
- src/e2etest/lcd.spec.ts
- src/lib/lcd.ts
- src/service/bank/getBalance/normalizeAccount.ts
- src/service/staking/getDelegators.ts
- src/service/staking/getValidatorReturn.ts
- src/service/staking/getValidators.ts
- src/service/staking/helper.ts
- src/service/transaction/helper.ts
- src/service/transaction/parseMsg.spec.ts
- src/types/lcd.d.ts
- src/types/rpc.d.ts
Due to heavy changes from staking module, I wanted to make codes up to date as much as possible.
> Refactor for Bombay

- package-lock.json
- package.json
- src/collector/collector.ts
- src/collector/staking/validatorDetails.ts
- src/collector/watcher.ts
refactor(collector/staking): self delegation calculation
fix(collector/watcher): resume logic
fix(collector): don't run collector validator at the beginning
> collector refactoring

- README.md
- src/config.ts
- src/service/treasury/pylon.ts
- src/service/treasury/token.ts
* environment variable
* Added PYLON_API_ENDPOINT (default: `https://api.dev.pylon.rocks/api`)
* circulating supply
* relays pylon api (`/mine/v1/overview`)
> feat: support $MINE token 

- src/lib/lcd.ts
Replace some inconsistent message types, which have inconsistent type name from its proto type name.
> Fix some inconsistent message codecs

- README.md
Docs have moved around since Columbus-5.
> docs: Update link to LCD

- package-lock.json
- package.json
- src/service/governance/helper/voteSummary.ts
- src/service/transaction/getTxList.ts
Distributes query requests to TypeORM replications for transaction queries (/v1/txs)
> Use reader endpoints for transaction queries

- package-lock.json
- package.json
- src/collector/block/general.ts
- src/service/transaction/getTxList.ts
This PR fixes SQL syntax error in transaction endpoint by account address with empty result 
Fix: #169
> Fix empty account txs
